Feat/server/command connect nbr
Eviber/zappy pull request #56
Opened 2023-11-26 20:12 UTC by Eviber

Fixes #47.

This branch is based on `client-buffer`, and should therefore be merged after #53.

This is just a proposition, there are other ways to do this.

2023-11-26 20:12 UTC, Eviber commented
(Just watch the last commit to see the changes.)

2023-11-29 14:17 UTC, Eviber commented
ok, it works but it feels sloppy, any ideas?

2023-12-09 16:41 UTC, Ragarnoy commented on crates/server/src/state/mod.rs
> +    ConnectNbr(u32),
MISSING DOC FUCK YOU

2023-12-09 16:42 UTC, Ragarnoy requested changes
DOC

2024-01-09 12:37 UTC, nils-mathieu approved these changes

2024-11-03 18:07 UTC, Ragarnoy approved these changes

2024-11-17 14:54 UTC, merged